### ISSUE TITLE
add STATIC_ROOT and MEDIA_URL info to readme

### ISSUE THREAD

**Issue by foobarbecue** [fmalina/upload#2]
I think both of these settings are required to get the app working, so that should be mentioned in the setup guide.

**Comment by foobarbecue** [comment]
And STATIC_URL. It's quite hard to figure how upload is expecting you to set all this stuff up.

**Comment by foobarbecue** [comment]
Is there source code available to a working implementation somewhere? That would make it easy...

**Comment by fmalina** [comment]
I have now addressed this. Thank you for your suggestion @foobarbecue.

**Comment by fmalina** [comment]
To see working implementation, just download the repository and run `./manage.py runserver`. You may need to install `easy_thumbnails`. See `upload/tests/test_settings.py`.
